test:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account
      project: storied-deck-378808
      dataset: dbt_test_big
      threads: 1
      timeout_seconds: 300
      location: US
      priority: interactive
      # keyfile: /path/to/your/service-account-key.json


      # 9614db6f5dc46477783f536f3686212df6c47989	